/**
 * Distinct, very-light pastel per-window colors.
 *
 * Colors are generated by walking the hue circle in golden-angle steps, so
 * consecutive windows are always well-separated and effectively unique. The hue
 * is used for the Windows Terminal tab color (`--tabColor`); an even lighter
 * version tints the whole background (OSC 11), paired with a dark foreground
 * (OSC 10) so text stays readable on the light background.
 */

/** Golden angle — successive multiples never cluster, giving distinct hues. */
const GOLDEN_ANGLE = 137.508

/** Very light pastel for the tab/accent color. */
const PASTEL_S = 0.7
const PASTEL_L = 0.86

/** Dark foreground used on the light pastel background, for readability. */
export const PANE_FG = "#23262b"

function hslToHex(h: number, s: number, l: number): string {
	const c = (1 - Math.abs(2 * l - 1)) * s
	const x = c * (1 - Math.abs(((h / 60) % 2) - 1))
	const m = l - c / 2
	let r = 0
	let g = 0
	let b = 0
	if (h < 60) [r, g] = [c, x]
	else if (h < 120) [r, g] = [x, c]
	else if (h < 180) [g, b] = [c, x]
	else if (h < 240) [g, b] = [x, c]
	else if (h < 300) [r, b] = [x, c]
	else [r, b] = [c, x]
	return toHex((r + m) * 255, (g + m) * 255, (b + m) * 255)
}

/** A unique very-light pastel hue for the n-th window. */
export function paletteColor(index: number): string {
	const hue = (((index * GOLDEN_ANGLE) % 360) + 360) % 360
	return hslToHex(hue, PASTEL_S, PASTEL_L)
}

function parseHex(hex: string): { r: number; g: number; b: number } {
	const h = hex.replace("#", "")
	return {
		r: Number.parseInt(h.slice(0, 2), 16),
		g: Number.parseInt(h.slice(2, 4), 16),
		b: Number.parseInt(h.slice(4, 6), 16),
	}
}

function toHex(r: number, g: number, b: number): string {
	const h = (n: number) =>
		Math.max(0, Math.min(255, Math.round(n)))
			.toString(16)
			.padStart(2, "0")
	return `#${h(r)}${h(g)}${h(b)}`
}

/**
 * Lighten `hex` toward white for a very pale background tint. `amount` is how
 * far toward white (0 = unchanged, 1 = white).
 */
export function lightTint(hex: string, amount = 0.62): string {
	const c = parseHex(hex)
	const mix = (x: number) => x + (255 - x) * amount
	return toHex(mix(c.r), mix(c.g), mix(c.b))
}

/** A 24-bit ANSI foreground escape for `hex` (for coloring terminal text). */
export function ansiFg(hex: string): string {
	const { r, g, b } = parseHex(hex)
	return `\x1b[38;2;${r};${g};${b}m`
}
